//! Rust backing modules for `std.derives.*` trait definitions.
//!
//! These modules exist as delegation targets for `@rust.extern` methods on derive traits. The actual trait
//! implementations are generated by Rust's `#[derive(...)]` proc macros on each adopting type; these modules
//! provide the namespace that `rust.module()` directives in the `.incn` sources point to.

pub mod comparison;
pub mod copying;
pub mod string;
