//! `incan.lock` parsing, validation, and fingerprinting.
//!
//! The lockfile embeds a Cargo.lock payload and records a dependency fingerprint
//! for strict `--locked` / `--frozen` builds.

use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::manifest::{DependencySource, DependencySpec, GitReference};

const LOCKFILE_FORMAT_VERSION: u32 = 1;

#[derive(Debug, thiserror::Error)]
pub enum LockfileError {
    #[error("failed to read {path}: {source}")]
    Read { path: PathBuf, source: std::io::Error },
    #[error("failed to write {path}: {source}")]
    Write { path: PathBuf, source: std::io::Error },
    #[error("failed to parse {path}: {source}")]
    Parse { path: PathBuf, source: toml::de::Error },
    #[error("failed to serialize lockfile: {0}")]
    Serialize(String),
    #[error("invalid lockfile {path}: {message}")]
    Invalid { path: PathBuf, message: String },
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CargoFeatureSelection {
    #[serde(rename = "cargo-features", default)]
    pub cargo_features: Vec<String>,
    #[serde(rename = "cargo-no-default-features", default)]
    pub cargo_no_default_features: bool,
    #[serde(rename = "cargo-all-features", default)]
    pub cargo_all_features: bool,
}

impl CargoFeatureSelection {
    pub fn normalized(mut self) -> Self {
        self.cargo_features.sort();
        self.cargo_features.dedup();
        self
    }
}

#[derive(Debug, Clone)]
pub struct IncanLock {
    pub format: u32,
    pub incan_version: String,
    pub deps_fingerprint: String,
    pub cargo_features: CargoFeatureSelection,
    pub cargo_lock_payload: String,
}

impl IncanLock {
    pub fn load(path: &Path) -> Result<Self, LockfileError> {
        let content = fs::read_to_string(path).map_err(|e| LockfileError::Read {
            path: path.to_path_buf(),
            source: e,
        })?;
        parse_lockfile(&content, path)
    }

    pub fn write(&self, path: &Path) -> Result<(), LockfileError> {
        let raw = RawIncanLock {
            incan: RawIncanMeta {
                format: self.format,
                incan_version: self.incan_version.clone(),
                deps_fingerprint: self.deps_fingerprint.clone(),
                cargo_features: self.cargo_features.cargo_features.clone(),
                cargo_no_default_features: self.cargo_features.cargo_no_default_features,
                cargo_all_features: self.cargo_features.cargo_all_features,
            },
            cargo: RawCargoLock {
                lock: self.cargo_lock_payload.clone(),
            },
        };

        let body = toml::to_string(&raw).map_err(|e| LockfileError::Serialize(e.to_string()))?;
        let content =
            format!("# Auto-generated by Incan - do not edit manually\n# Regenerate with: incan lock\n\n{body}");
        fs::write(path, content).map_err(|e| LockfileError::Write {
            path: path.to_path_buf(),
            source: e,
        })?;
        Ok(())
    }

    pub fn new(deps_fingerprint: String, cargo_features: CargoFeatureSelection, cargo_lock_payload: String) -> Self {
        Self {
            format: LOCKFILE_FORMAT_VERSION,
            incan_version: crate::version::INCAN_VERSION.to_string(),
            deps_fingerprint,
            cargo_features: cargo_features.normalized(),
            cargo_lock_payload: normalize_cargo_lock_payload(&cargo_lock_payload),
        }
    }
}

/// Compute a stable SHA-256 fingerprint over the effective dependency specs and Cargo feature selection.
///
/// ## Parameters
///
/// - `project_root`: When provided, `path:` dependency sources are relativized to this directory so the fingerprint is
///   portable across machines (RFC 013 Appendix A.2).
pub fn compute_deps_fingerprint(
    dependencies: &[DependencySpec],
    dev_dependencies: &[DependencySpec],
    cargo_features: &CargoFeatureSelection,
    project_root: Option<&Path>,
) -> String {
    let mut specs = Vec::new();

    for spec in dependencies {
        specs.push(SpecFingerprint::from_spec(spec, "normal", project_root));
    }
    for spec in dev_dependencies {
        specs.push(SpecFingerprint::from_spec(spec, "dev", project_root));
    }

    specs.sort_by(|a, b| (a.kind.as_str(), a.crate_name.as_str()).cmp(&(b.kind.as_str(), b.crate_name.as_str())));

    let input = FingerprintInput {
        cargo_feature_selection: CargoFeatureSelectionFingerprint::from_selection(cargo_features),
        specs,
    };
    let json = serde_json::to_string(&input).unwrap_or_else(|_| "{}".to_string());
    let mut hasher = Sha256::new();
    hasher.update(json.as_bytes());
    let hash = hasher.finalize();
    format!("sha256:{}", hex::encode(hash))
}

pub fn normalize_cargo_lock_payload(payload: &str) -> String {
    let mut out = payload.replace("\r\n", "\n");
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

fn parse_lockfile(content: &str, path: &Path) -> Result<IncanLock, LockfileError> {
    let raw: RawIncanLock = toml::from_str(content).map_err(|e| LockfileError::Parse {
        path: path.to_path_buf(),
        source: e,
    })?;

    if raw.incan.format != LOCKFILE_FORMAT_VERSION {
        return Err(LockfileError::Invalid {
            path: path.to_path_buf(),
            message: format!(
                "unsupported lockfile format {} (expected {})",
                raw.incan.format, LOCKFILE_FORMAT_VERSION
            ),
        });
    }

    Ok(IncanLock {
        format: raw.incan.format,
        incan_version: raw.incan.incan_version,
        deps_fingerprint: raw.incan.deps_fingerprint,
        cargo_features: CargoFeatureSelection {
            cargo_features: raw.incan.cargo_features,
            cargo_no_default_features: raw.incan.cargo_no_default_features,
            cargo_all_features: raw.incan.cargo_all_features,
        }
        .normalized(),
        cargo_lock_payload: normalize_cargo_lock_payload(&raw.cargo.lock),
    })
}

#[derive(Debug, Serialize, Deserialize)]
struct RawIncanLock {
    incan: RawIncanMeta,
    cargo: RawCargoLock,
}

#[derive(Debug, Serialize, Deserialize)]
struct RawIncanMeta {
    format: u32,
    #[serde(rename = "incan-version")]
    incan_version: String,
    #[serde(rename = "deps-fingerprint")]
    deps_fingerprint: String,
    #[serde(rename = "cargo-features", default)]
    cargo_features: Vec<String>,
    #[serde(rename = "cargo-no-default-features", default)]
    cargo_no_default_features: bool,
    #[serde(rename = "cargo-all-features", default)]
    cargo_all_features: bool,
}

#[derive(Debug, Serialize, Deserialize)]
struct RawCargoLock {
    lock: String,
}

#[derive(Debug, Serialize)]
struct FingerprintInput {
    cargo_feature_selection: CargoFeatureSelectionFingerprint,
    specs: Vec<SpecFingerprint>,
}

#[derive(Debug, Serialize)]
struct CargoFeatureSelectionFingerprint {
    cargo_all_features: bool,
    cargo_no_default_features: bool,
    cargo_features: Vec<String>,
}

impl CargoFeatureSelectionFingerprint {
    fn from_selection(selection: &CargoFeatureSelection) -> Self {
        let mut features = selection.cargo_features.clone();
        features.sort();
        features.dedup();
        Self {
            cargo_all_features: selection.cargo_all_features,
            cargo_no_default_features: selection.cargo_no_default_features,
            cargo_features: features,
        }
    }
}

#[derive(Debug, Serialize)]
struct SpecFingerprint {
    crate_name: String,
    kind: String,
    source: String,
    version_req: Option<String>,
    default_features: bool,
    features: Vec<String>,
    optional: bool,
    package: Option<String>,
}

impl SpecFingerprint {
    fn from_spec(spec: &DependencySpec, kind: &str, project_root: Option<&Path>) -> Self {
        let mut features = spec.features.clone();
        features.sort();
        features.dedup();

        Self {
            crate_name: spec.crate_name.clone(),
            kind: kind.to_string(),
            source: source_fingerprint(&spec.source, project_root),
            version_req: spec.version.as_deref().map(normalize_version_req),
            default_features: spec.default_features,
            features,
            optional: spec.optional,
            package: spec.package.clone(),
        }
    }
}

/// Produce a stable, portable string for a dependency source.
///
/// For `Path` sources, strips `project_root` when available so the fingerprint doesn't change across machines with
/// different absolute paths (RFC 013 Appendix A.2).
fn source_fingerprint(source: &DependencySource, project_root: Option<&Path>) -> String {
    match source {
        DependencySource::Registry => "registry".to_string(),
        DependencySource::Git { url, reference } => match reference {
            GitReference::Branch(branch) => format!("git:{url}#branch:{branch}"),
            GitReference::Tag(tag) => format!("git:{url}#tag:{tag}"),
            GitReference::Rev(rev) => format!("git:{url}#rev:{rev}"),
        },
        DependencySource::Path { path } => {
            let relative = project_root
                .and_then(|root| path.strip_prefix(root).ok())
                .unwrap_or(path);
            let normalized = normalize_relative_path_for_fingerprint(relative);
            format!("path:{}", normalized.to_string_lossy().replace('\\', "/"))
        }
    }
}

fn normalize_relative_path_for_fingerprint(path: &Path) -> PathBuf {
    if path.is_absolute() {
        return path.to_path_buf();
    }

    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            std::path::Component::CurDir => {}
            std::path::Component::Normal(segment) => normalized.push(segment),
            std::path::Component::ParentDir => normalized.push(".."),
            std::path::Component::Prefix(prefix) => normalized.push(prefix.as_os_str()),
            std::path::Component::RootDir => normalized.push(component.as_os_str()),
        }
    }
    normalized
}

fn normalize_version_req(input: &str) -> String {
    input.split_whitespace().collect::<Vec<_>>().join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    type TestResult = Result<(), Box<dyn std::error::Error>>;

    fn sample_spec(name: &str, features: Vec<&str>) -> DependencySpec {
        DependencySpec {
            crate_name: name.to_string(),
            version: Some("1.0".to_string()),
            features: features.into_iter().map(|f| f.to_string()).collect(),
            default_features: true,
            source: DependencySource::Registry,
            optional: false,
            package: None,
        }
    }

    #[test]
    fn fingerprint_is_stable_across_feature_order() {
        let deps = vec![sample_spec("alpha", vec!["b", "a"])];
        let deps_reordered = vec![sample_spec("alpha", vec!["a", "b"])];
        let selection = CargoFeatureSelection::default();

        let first = compute_deps_fingerprint(&deps, &[], &selection, None);
        let second = compute_deps_fingerprint(&deps_reordered, &[], &selection, None);
        assert_eq!(first, second);
    }

    #[test]
    fn lockfile_round_trip() -> TestResult {
        let selection = CargoFeatureSelection {
            cargo_features: vec!["alpha".to_string()],
            cargo_no_default_features: false,
            cargo_all_features: false,
        };
        let lock = IncanLock::new(
            "sha256:deadbeef".to_string(),
            selection,
            "[[package]]\nname = \"x\"\n".to_string(),
        );

        let dir = tempfile::tempdir()?;
        let path = dir.path().join("incan.lock");
        lock.write(&path)?;

        let content = std::fs::read_to_string(&path)?;
        assert!(
            !content.contains("generated ="),
            "lockfiles should not contain volatile generation timestamps"
        );
        let loaded = IncanLock::load(&path)?;
        assert_eq!(loaded.deps_fingerprint, "sha256:deadbeef");
        assert_eq!(loaded.cargo_features.cargo_features, vec!["alpha".to_string()]);
        assert!(loaded.cargo_lock_payload.contains("package"));
        Ok(())
    }

    #[test]
    fn legacy_generated_timestamp_is_accepted_on_load() -> TestResult {
        let dir = tempfile::tempdir()?;
        let path = dir.path().join("incan.lock");
        let legacy_toml = r#"
[incan]
format = 1
incan-version = "0.3.0-dev.23"
generated = "2026-04-27T13:41:45.845714Z"
deps-fingerprint = "sha256:abc"
cargo-features = []
cargo-no-default-features = false
cargo-all-features = false

[cargo]
lock = "payload"
"#;
        std::fs::write(&path, legacy_toml)?;

        let lock = IncanLock::load(&path)?;
        assert_eq!(lock.deps_fingerprint, "sha256:abc");
        assert_eq!(lock.cargo_lock_payload, "payload\n");
        Ok(())
    }

    // ---- Phase 4: fingerprint changes when deps change ----

    #[test]
    fn fingerprint_changes_when_deps_differ() {
        let deps_a = vec![sample_spec("alpha", vec!["a"])];
        let deps_b = vec![sample_spec("alpha", vec!["a", "b"])];
        let selection = CargoFeatureSelection::default();

        let fp_a = compute_deps_fingerprint(&deps_a, &[], &selection, None);
        let fp_b = compute_deps_fingerprint(&deps_b, &[], &selection, None);
        assert_ne!(fp_a, fp_b, "fingerprints should differ when features differ");
    }

    #[test]
    fn path_dependency_fingerprint_normalizes_current_dir_segments() {
        let mut dep_plain = sample_spec("tiny_helper", vec![]);
        dep_plain.source = DependencySource::Path {
            path: PathBuf::from("rust/tiny_helper"),
        };
        let mut dep_current_dir = dep_plain.clone();
        dep_current_dir.source = DependencySource::Path {
            path: PathBuf::from("./rust/tiny_helper"),
        };
        let selection = CargoFeatureSelection::default();

        assert_eq!(
            compute_deps_fingerprint(&[dep_plain], &[], &selection, Some(Path::new("."))),
            compute_deps_fingerprint(&[dep_current_dir], &[], &selection, Some(Path::new("."))),
        );
    }

    // ---- Phase 4: stale fingerprint detection ----

    #[test]
    fn stale_fingerprint_is_detectable() {
        let selection = CargoFeatureSelection::default();
        let deps_v1 = vec![sample_spec("alpha", vec!["a"])];
        let fp_v1 = compute_deps_fingerprint(&deps_v1, &[], &selection, None);

        let lock = IncanLock::new(fp_v1.clone(), selection.clone(), "payload".to_string());

        // Simulate deps changing
        let deps_v2 = vec![sample_spec("alpha", vec!["a", "new_feature"])];
        let fp_v2 = compute_deps_fingerprint(&deps_v2, &[], &selection, None);

        assert_ne!(
            lock.deps_fingerprint, fp_v2,
            "lock fingerprint should not match updated deps"
        );
    }

    // ---- Phase 4: Cargo.lock materialization via ProjectGenerator ----

    #[test]
    fn cargo_lock_payload_materializes_in_project() -> TestResult {
        use std::fs;

        let temp_dir = tempfile::tempdir()?;
        let project_dir = temp_dir.path().join("test_lock_project");

        let mut generator = crate::backend::ProjectGenerator::new(&project_dir, "test_lock", true);
        generator.set_cargo_lock_payload(Some("[[package]]\nname = \"hello\"\nversion = \"0.1.0\"\n".to_string()));

        generator.generate("fn main() {}")?;

        let cargo_lock_path = project_dir.join("Cargo.lock");
        assert!(cargo_lock_path.exists(), "Cargo.lock should be written to project dir");
        let content = fs::read_to_string(&cargo_lock_path)?;
        assert!(
            content.contains("hello"),
            "Cargo.lock should contain the payload, got:\n{content}"
        );
        Ok(())
    }

    // ---- Phase 4: format version is validated on load ----

    #[test]
    fn lockfile_format_version_checked() -> TestResult {
        let dir = tempfile::tempdir()?;
        let path = dir.path().join("incan.lock");

        // Write a lockfile with an incompatible format version
        let bad_toml = r#"
[incan]
format = 999
incan-version = "0.1.0"
generated = "2025-01-01T00:00:00Z"
deps-fingerprint = "sha256:abc"
cargo-features = []
cargo-no-default-features = false
cargo-all-features = false

[cargo]
lock = "payload"
"#;
        std::fs::write(&path, bad_toml)?;
        let result = IncanLock::load(&path);
        assert!(result.is_err(), "loading a future format version should fail");
        Ok(())
    }

    // ---- CargoFeatureSelection normalization ----

    #[test]
    fn cargo_feature_selection_normalized() {
        let sel = CargoFeatureSelection {
            cargo_features: vec!["b".to_string(), "a".to_string(), "a".to_string()],
            cargo_no_default_features: false,
            cargo_all_features: false,
        };
        let norm = sel.normalized();
        assert_eq!(norm.cargo_features, vec!["a".to_string(), "b".to_string()]);
    }
}
